# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rWiEUOdVgA2Jjv7qbl6CPnHNBFiVz0lg
"""

!pip install scikit-learn

!pip install streamlit

import streamlit as st
import pickle
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import os

# Set a title for the app
st.title("Salary Prediction App")

# Define the paths to the model and data
MODEL_PATH = 'random_forest_model.pkl'
DATA_PATH = 'Salary_Data.csv' # Used to consistently set up LabelEncoders

# Check if model and data files exist
if not os.path.exists(MODEL_PATH):
    st.error(f"Error: Model file not found at {MODEL_PATH}. Please ensure it's in the same directory as this app.py file.")
    st.stop()
if not os.path.exists(DATA_PATH):
    st.error(f"Error: Data file not found at {DATA_PATH}. Please ensure it's in the same directory as this app.py file.")
    st.stop()

# Load the trained model
try:
    with open(MODEL_PATH, 'rb') as file:
        model = pickle.load(file)
    st.success("Model loaded successfully!")
except Exception as e:
    st.error(f"Error loading model: {e}")
    st.stop()

# Load the original dataframe to fit LabelEncoders consistently
try:
    original_df = pd.read_csv(DATA_PATH)
    st.success("Original data loaded for LabelEncoder setup.")
except Exception as e:
    st.error(f"Error loading original data: {e}")
    st.stop()


# Replicate preprocessing steps for categorical columns to fit LabelEncoders
# Fill null values for categorical columns (mode) before fitting LabelEncoder
for column in ['Gender', 'Education Level', 'Job Title']:
    if original_df[column].dtype == 'object':
        original_df[column] = original_df[column].fillna(original_df[column].mode()[0])

# Initialize and fit LabelEncoders for categorical features using the cleaned original data
label_encoders = {}
categorical_cols = ['Gender', 'Education Level', 'Job Title']

for col in categorical_cols:
    le = LabelEncoder()
    # Fit the encoder on the cleaned, original data column to ensure consistent mapping
    le.fit(original_df[col])
    label_encoders[col] = le

st.sidebar.header("User Input Features")

def user_input_features():
    age = st.sidebar.slider('Age', 18, 65, 30)

    # Get options directly from the fitted LabelEncoder classes
    gender_options = label_encoders['Gender'].classes_.tolist()
    gender = st.sidebar.selectbox('Gender', gender_options)

    education_options = label_encoders['Education Level'].classes_.tolist()
    education_level = st.sidebar.selectbox('Education Level', education_options)

    job_options = label_encoders['Job Title'].classes_.tolist()
    job_title = st.sidebar.selectbox('Job Title', job_options)

    years_experience = st.sidebar.slider('Years of Experience', 0, 40, 5)

    data = {
        'Age': age,
        'Gender': gender,
        'Education Level': education_level,
        'Job Title': job_title,
        'Years of Experience': years_experience
    }
    features = pd.DataFrame(data, index=[0])
    return features

input_df = user_input_features()

st.subheader("User Input Data")
st.write(input_df)

# Apply Label Encoding to user input using the fitted encoders
processed_input = input_df.copy()
for col in categorical_cols:
    # Use the fitted encoder to transform the user's input
    processed_input[col] = label_encoders[col].transform(processed_input[col])

st.subheader("Processed Input Data (for model)")
st.write(processed_input)

# Make prediction
if st.button('Predict Salary'):
    try:
        prediction = model.predict(processed_input)
        st.subheader("Predicted Salary")
        st.write(f"The predicted salary is: ${prediction[0]:,.2f}")
    except Exception as e:
        st.error(f"Error during prediction: {e}")