# -*- coding: utf-8 -*-
"""ModelBuilding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UsPhXQT95Xq3Ddv35CBf3CC8fTBif7Tv
"""

!pip install scikit-learn

import pandas as pd

df = pd.read_csv("/content/Salary_Data.csv")

df

df.isnull().sum() #checks if there is any null data in dataset

for column in df.columns:
  if df[column].dtype == 'object':
    #Fill categorical columns with the mode
    df[column] = df[column].fillna(df[column].mode()[0])
  else:
    #Fill numerical columns with the mean
    df[column] = df[column].fillna(df[column].mean())
print(df.isnull().sum())

from sklearn.preprocessing import LabelEncoder #label encoder takes only categorical data

label_encoder = LabelEncoder()
for column in ['Gender','Education Level','Job Title']:
  df[column] = label_encoder.fit_transform(df[column])

print(df.head())

from sklearn.model_selection import train_test_split

x = df.drop('Salary', axis=1)
y = df['Salary']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, r2_score

from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import numpy as np

models = {
    'Linear Regression': LinearRegression(),
    'Decision Tree': DecisionTreeRegressor(random_state=42),
    'Random Forest': RandomForestRegressor(random_state=42),
    'Support Vector Regressor': SVR(),
    'K-Neighbors Regressor': KNeighborsRegressor()
}

results = {}

for name, model in models.items():
    print(f"Training {name}...")
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    results[name] = {'MSE': mse, 'RMSE': rmse, 'MAE': mae, 'R2': r2}
    print(f"{name} - MSE: {mse:.2f}, RMSE: {rmse:.2f}, MAE: {mae:.2f}, R2: {r2:.2f}\n")

print("\n--- Model Performance Comparison ---")
for name, metrics in results.items():
    print(f"{name}:\n  Mean Squared Error (MSE): {metrics['MSE']:.2f}\n  Root Mean Squared Error (RMSE): {metrics['RMSE']:.2f}\n  Mean Absolute Error (MAE): {metrics['MAE']:.2f}\n  R-squared (R2): {metrics['R2']:.2f}\n")

import matplotlib.pyplot as plt
import pandas as pd

# Extract R2 scores for plotting
r2_scores = {name: metrics['R2'] for name, metrics in results.items()}
model_names = list(r2_scores.keys())
r2_values = list(r2_scores.values())

# Create a DataFrame for easier plotting
r2_df = pd.DataFrame({
    'Model': model_names,
    'R2 Score': r2_values
})

# Sort by R2 Score for better visualization
r2_df = r2_df.sort_values(by='R2 Score', ascending=False)

plt.figure(figsize=(10, 6))
plt.bar(r2_df['Model'], r2_df['R2 Score'], color='skyblue')
plt.xlabel('Regression Model')
plt.ylabel('R-squared (R2) Score')
plt.title('Comparison of R-squared Scores for Different Regression Models')
plt.ylim(0, 1) # R2 scores are between 0 and 1
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

import pickle

# Find the best model based on R2 score
best_model_name = max(results, key=lambda k: results[k]['R2'])
best_model = models[best_model_name]

# Define the filename for the saved model
model_filename = f'{best_model_name.replace(" ", "_").lower()}_model.pkl'

# Save the best model to a .pkl file
with open(model_filename, 'wb') as file:
    pickle.dump(best_model, file)

print(f"Best model ('{best_model_name}') saved to {model_filename}")

